package smartspace;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import smartspace.dao.rdb.RdbElementDao;
import smartspace.dao.rdb.RdbUserDao;
import smartspace.data.ElementEntity;
import smartspace.data.Location;
import smartspace.data.UserEntity;
import smartspace.data.UserRole;

@Component
@ConditionalOnProperty(name = "spring.datasource.initialization-mode", havingValue = "always")

public class DBinitializer implements CommandLineRunner {

	private RdbUserDao rdbUserDao;
	private RdbElementDao rdbElementDao;
	
	 public DBinitializer(RdbUserDao rdbUserDao , RdbElementDao rdbElementDao) {
		 this.rdbUserDao = rdbUserDao;
		 this.rdbElementDao = rdbElementDao;
	 }
	 
	 @Override
	 public void run(String...strings) throws Exception {
		 UserEntity userAdmin = new UserEntity
				 ("rita@snakeLadder.com", "2019b.marlenba" , "rita" , ":)", UserRole.ADMIN, (long)0);
		/* 
		 ElementEntity snake1 = new ElementEntity("snake1", "LadderSnake", new Location(2, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity snake2 = new ElementEntity("snake2", "LadderSnake", new Location(2, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity snake3 = new ElementEntity("snake3", "LadderSnake", new Location(6, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity snake4 = new ElementEntity("snake4", "LadderSnake", new Location(6, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity snake5 = new ElementEntity("snake5", "LadderSnake", new Location(1, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 
		 ElementEntity ladder1 = new ElementEntity("ladder1", "LadderSnake", new Location(4, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity ladder2 = new ElementEntity("ladder2", "LadderSnake", new Location(2, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity ladder3 = new ElementEntity("ladder3", "LadderSnake", new Location(4, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity ladder4 = new ElementEntity("ladder4", "LadderSnake", new Location(9, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity ladder5 = new ElementEntity("ladder5", "LadderSnake", new Location(9, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity ladder6 = new ElementEntity("ladder6", "LadderSnake", new Location(10, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 
		 ElementEntity trapoline1 = new ElementEntity("trapoline1", "LadderSnake", new Location(2, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity trapoline2 = new ElementEntity("trapoline2", "LadderSnake", new Location(3, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity trapoline3 = new ElementEntity("trapoline3", "LadderSnake", new Location(7, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);
		 ElementEntity trapoline4 = new ElementEntity("trapoline4", "LadderSnake", new Location(9, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", null);

		 
		 ElementEntity tile1 = new ElementEntity("tile1", "Tile", new Location(1, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile2 = new ElementEntity("tile2", "Tile", new Location(1, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile3 = new ElementEntity("tile3", "Tile", new Location(1, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile4 = new ElementEntity("tile4", "Tile", new Location(1, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile5 = new ElementEntity("tile5", "Tile", new Location(1, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile6 = new ElementEntity("tile6", "Tile", new Location(1, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile7 = new ElementEntity("tile7", "Tile", new Location(1, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile8 = new ElementEntity("tile8", "Tile", new Location(1, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile9 = new ElementEntity("tile9", "Tile", new Location(1, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile10 = new ElementEntity("tile10", "Tile", new Location(1, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile11 = new ElementEntity("tile11", "Tile", new Location(2, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile12 = new ElementEntity("tile12", "Tile", new Location(2, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile13 = new ElementEntity("tile13", "Tile", new Location(2, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile14 = new ElementEntity("tile14", "Tile", new Location(2, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile15 = new ElementEntity("tile15", "Tile", new Location(2, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile16 = new ElementEntity("tile16", "Tile", new Location(2, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile17 = new ElementEntity("tile17", "Tile", new Location(2, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile18 = new ElementEntity("tile18", "Tile", new Location(2, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile19 = new ElementEntity("tile19", "Tile", new Location(2, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile20 = new ElementEntity("tile20", "Tile", new Location(2, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile21 = new ElementEntity("tile21", "Tile", new Location(3, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile22 = new ElementEntity("tile22", "Tile", new Location(3, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile23 = new ElementEntity("tile23", "Tile", new Location(3, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile24 = new ElementEntity("tile24", "Tile", new Location(3, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile25 = new ElementEntity("tile25", "Tile", new Location(3, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile26 = new ElementEntity("tile26", "Tile", new Location(3, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile27 = new ElementEntity("tile27", "Tile", new Location(3, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile28 = new ElementEntity("tile28", "Tile", new Location(3, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile29 = new ElementEntity("tile29", "Tile", new Location(3, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile30 = new ElementEntity("tile30", "Tile", new Location(3, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile31 = new ElementEntity("tile31", "Tile", new Location(4, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile32 = new ElementEntity("tile32", "Tile", new Location(4, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile33 = new ElementEntity("tile33", "Tile", new Location(4, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile34 = new ElementEntity("tile34", "Tile", new Location(4, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile35 = new ElementEntity("tile35", "Tile", new Location(4, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile36 = new ElementEntity("tile36", "Tile", new Location(4, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile37 = new ElementEntity("tile37", "Tile", new Location(4, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile38 = new ElementEntity("tile38", "Tile", new Location(4, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile39 = new ElementEntity("tile39", "Tile", new Location(4, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile40 = new ElementEntity("tile40", "Tile", new Location(4, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile41 = new ElementEntity("tile41", "Tile", new Location(5, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile42 = new ElementEntity("tile42", "Tile", new Location(5, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile43 = new ElementEntity("tile43", "Tile", new Location(5, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile44 = new ElementEntity("tile44", "Tile", new Location(5, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile45 = new ElementEntity("tile45", "Tile", new Location(5, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile46 = new ElementEntity("tile46", "Tile", new Location(5, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile47 = new ElementEntity("tile47", "Tile", new Location(5, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile48 = new ElementEntity("tile48", "Tile", new Location(5, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile49 = new ElementEntity("tile49", "Tile", new Location(5, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile50 = new ElementEntity("tile50", "Tile", new Location(5, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile51 = new ElementEntity("tile51", "Tile", new Location(6, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile52 = new ElementEntity("tile52", "Tile", new Location(6, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile53 = new ElementEntity("tile53", "Tile", new Location(6, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile54 = new ElementEntity("tile54", "Tile", new Location(6, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile55 = new ElementEntity("tile55", "Tile", new Location(6, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile56 = new ElementEntity("tile56", "Tile", new Location(6, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile57 = new ElementEntity("tile57", "Tile", new Location(6, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile58 = new ElementEntity("tile58", "Tile", new Location(6, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile59 = new ElementEntity("tile59", "Tile", new Location(6, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile60 = new ElementEntity("tile60", "Tile", new Location(6, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile61 = new ElementEntity("tile61", "Tile", new Location(7, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile62 = new ElementEntity("tile62", "Tile", new Location(7, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile63 = new ElementEntity("tile63", "Tile", new Location(7, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile64 = new ElementEntity("tile64", "Tile", new Location(7, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile65 = new ElementEntity("tile65", "Tile", new Location(7, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile66 = new ElementEntity("tile66", "Tile", new Location(7, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile67 = new ElementEntity("tile67", "Tile", new Location(7, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile68 = new ElementEntity("tile68", "Tile", new Location(7, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile69 = new ElementEntity("tile69", "Tile", new Location(7, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile70 = new ElementEntity("tile70", "Tile", new Location(7, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile71 = new ElementEntity("tile71", "Tile", new Location(8, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile72 = new ElementEntity("tile72", "Tile", new Location(8, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile73 = new ElementEntity("tile73", "Tile", new Location(8, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile74 = new ElementEntity("tile74", "Tile", new Location(8, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile75 = new ElementEntity("tile75", "Tile", new Location(8, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile76 = new ElementEntity("tile76", "Tile", new Location(8, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile77 = new ElementEntity("tile77", "Tile", new Location(8, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile78 = new ElementEntity("tile78", "Tile", new Location(8, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile79 = new ElementEntity("tile79", "Tile", new Location(8, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile80 = new ElementEntity("tile80", "Tile", new Location(8, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile81 = new ElementEntity("tile81", "Tile", new Location(9, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile82 = new ElementEntity("tile82", "Tile", new Location(9, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile83 = new ElementEntity("tile83", "Tile", new Location(9, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile84 = new ElementEntity("tile84", "Tile", new Location(9, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile85 = new ElementEntity("tile85", "Tile", new Location(9, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile86 = new ElementEntity("tile86", "Tile", new Location(9, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile87 = new ElementEntity("tile87", "Tile", new Location(9, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile88 = new ElementEntity("tile88", "Tile", new Location(9, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile89 = new ElementEntity("tile89", "Tile", new Location(9, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile90 = new ElementEntity("tile90", "Tile", new Location(9, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile91 = new ElementEntity("tile91", "Tile", new Location(10, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile92 = new ElementEntity("tile92", "Tile", new Location(10, 2), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile93 = new ElementEntity("tile93", "Tile", new Location(10, 3), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile94 = new ElementEntity("tile94", "Tile", new Location(10, 4), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile95 = new ElementEntity("tile95", "Tile", new Location(10, 5), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile96 = new ElementEntity("tile96", "Tile", new Location(10, 6), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile97 = new ElementEntity("tile97", "Tile", new Location(10, 7), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile98 = new ElementEntity("tile98", "Tile", new Location(10, 8), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile99 = new ElementEntity("tile99", "Tile", new Location(10, 9), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		 ElementEntity tile100 = new ElementEntity("tile100", "Tile", new Location(10, 10), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", new HashMap<String, Object>());
		  Map<String, Object> cellMap = new HashMap<String, Object>();
		 cellMap.put("1", tile1);
		 cellMap.put("2", tile2);
		 cellMap.put("3", tile3);
		 cellMap.put("4", tile4);
		 cellMap.put("5", tile5);
		 cellMap.put("6", tile6);
		 cellMap.put("7", tile7);
		 cellMap.put("8", tile8);
		 cellMap.put("9", tile9);
		 cellMap.put("10", tile10);
		 cellMap.put("11", tile11);
		 cellMap.put("12", tile12);
		 cellMap.put("13", tile13);
		 cellMap.put("14", tile14);
		 cellMap.put("15", tile15);
		 cellMap.put("16", tile16);
		 cellMap.put("17", tile17);
		 cellMap.put("18", tile18);
		 cellMap.put("19", tile19);
		 cellMap.put("20", tile20);
		 cellMap.put("21", tile21);
		 cellMap.put("22", tile22);
		 cellMap.put("23", tile23);
		 cellMap.put("24", tile24);
		 cellMap.put("25", tile25);
		 cellMap.put("26", tile26);
		 cellMap.put("27", tile27);
		 cellMap.put("28", tile28);
		 cellMap.put("29", tile29);
		 cellMap.put("30", tile30);
		 cellMap.put("31", tile31);
		 cellMap.put("32", tile32);
		 cellMap.put("33", tile33);
		 cellMap.put("34", tile34);
		 cellMap.put("35", tile35);
		 cellMap.put("36", tile36);
		 cellMap.put("37", tile37);
		 cellMap.put("38", tile38);
		 cellMap.put("39", tile39);
		 cellMap.put("40", tile40);
		 cellMap.put("41", tile41);
		 cellMap.put("42", tile42);
		 cellMap.put("43", tile43);
		 cellMap.put("44", tile44);
		 cellMap.put("45", tile45);
		 cellMap.put("46", tile46);
		 cellMap.put("47", tile47);
		 cellMap.put("48", tile48);
		 cellMap.put("49", tile49);
		 cellMap.put("50", tile50);
		 cellMap.put("51", tile51);
		 cellMap.put("52", tile52);
		 cellMap.put("53", tile53);
		 cellMap.put("54", tile54);
		 cellMap.put("55", tile55);
		 cellMap.put("56", tile56);
		 cellMap.put("57", tile57);
		 cellMap.put("58", tile58);
		 cellMap.put("59", tile59);
		 cellMap.put("60", tile60);
		 cellMap.put("61", tile61);
		 cellMap.put("62", tile62);
		 cellMap.put("63", tile63);
		 cellMap.put("64", tile64);
		 cellMap.put("65", tile65);
		 cellMap.put("66", tile66);
		 cellMap.put("67", tile67);
		 cellMap.put("68", tile68);
		 cellMap.put("69", tile69);
		 cellMap.put("70", tile70);
		 cellMap.put("71", tile71);
		 cellMap.put("72", tile72);
		 cellMap.put("73", tile73);
		 cellMap.put("74", tile74);
		 cellMap.put("75", tile75);
		 cellMap.put("76", tile76);
		 cellMap.put("77", tile77);
		 cellMap.put("78", tile78);
		 cellMap.put("79", tile79);
		 cellMap.put("80", tile80);
		 cellMap.put("81", tile81);
		 cellMap.put("82", tile82);
		 cellMap.put("83", tile83);
		 cellMap.put("84", tile84);
		 cellMap.put("85", tile85);
		 cellMap.put("86", tile86);
		 cellMap.put("87", tile87);
		 cellMap.put("88", tile88);
		 cellMap.put("89", tile89);
		 cellMap.put("90", tile90);
		 cellMap.put("91", tile91);
		 cellMap.put("92", tile92);
		 cellMap.put("93", tile93);
		 cellMap.put("94", tile94);
		 cellMap.put("95", tile95);
		 cellMap.put("96", tile96);
		 cellMap.put("97", tile97);
		 cellMap.put("98", tile98);
		 cellMap.put("99", tile99);
		 cellMap.put("100", tile100);
		 
		 tile60.addToAttributesMap("snake", snake1);
		 tile55.addToAttributesMap("snake", snake2);
		 tile62.addToAttributesMap("snake", snake3);
		 tile99.addToAttributesMap("snake", snake4);
		 tile93.addToAttributesMap("snake", snake5);
		 
		 tile2.addToAttributesMap("ladder", ladder1);
		 tile4.addToAttributesMap("ladder", ladder2);
		 tile9.addToAttributesMap("ladder", ladder3);
		 tile38.addToAttributesMap("ladder", ladder4);
		 tile59.addToAttributesMap("ladder", ladder5);
		 tile71.addToAttributesMap("ladder", ladder6);
		 
		 tile14.addToAttributesMap("trampoline", trapoline1);
		 tile28.addToAttributesMap("trampoline", trapoline2);
		 tile63.addToAttributesMap("trampoline", trapoline3);
		 tile87.addToAttributesMap("trampoline", trapoline4);


		 ElementEntity board = new ElementEntity
				 ("board", "Board", new Location(1, 1), false, new Date(), "2019b.marlenba", "rita@snakeLadder.com", cellMap);
		*/ 
		 this.rdbUserDao.create(userAdmin);
		/* this.rdbElementDao.create(tile1);
		 this.rdbElementDao.create(tile2);
		 this.rdbElementDao.create(tile3);
		 this.rdbElementDao.create(tile4);
		 this.rdbElementDao.create(tile5);
		 this.rdbElementDao.create(tile6);
		 this.rdbElementDao.create(tile7);
		 this.rdbElementDao.create(tile8);
		 this.rdbElementDao.create(tile9);
		 this.rdbElementDao.create(tile10);
		 this.rdbElementDao.create(tile11);
		 this.rdbElementDao.create(tile12);
		 this.rdbElementDao.create(tile13);
		 this.rdbElementDao.create(tile14);
		 this.rdbElementDao.create(tile15);
		 this.rdbElementDao.create(tile16);
		 this.rdbElementDao.create(tile17);
		 this.rdbElementDao.create(tile18);
		 this.rdbElementDao.create(tile19);
		 this.rdbElementDao.create(tile20);
		 this.rdbElementDao.create(tile21);
		 this.rdbElementDao.create(tile22);
		 this.rdbElementDao.create(tile23);
		 this.rdbElementDao.create(tile24);
		 this.rdbElementDao.create(tile25);
		 this.rdbElementDao.create(tile26);
		 this.rdbElementDao.create(tile27);
		 this.rdbElementDao.create(tile28);
		 this.rdbElementDao.create(tile29);
		 this.rdbElementDao.create(tile30);
		 this.rdbElementDao.create(tile31);
		 this.rdbElementDao.create(tile32);
		 this.rdbElementDao.create(tile33);
		 this.rdbElementDao.create(tile34);
		 this.rdbElementDao.create(tile35);
		 this.rdbElementDao.create(tile36);
		 this.rdbElementDao.create(tile37);
		 this.rdbElementDao.create(tile38);
		 this.rdbElementDao.create(tile39);
		 this.rdbElementDao.create(tile40);
		 this.rdbElementDao.create(tile41);
		 this.rdbElementDao.create(tile42);
		 this.rdbElementDao.create(tile43);
		 this.rdbElementDao.create(tile44);
		 this.rdbElementDao.create(tile45);
		 this.rdbElementDao.create(tile46);
		 this.rdbElementDao.create(tile47);
		 this.rdbElementDao.create(tile48);
		 this.rdbElementDao.create(tile49);
		 this.rdbElementDao.create(tile50);
		 this.rdbElementDao.create(tile51);
		 this.rdbElementDao.create(tile52);
		 this.rdbElementDao.create(tile53);
		 this.rdbElementDao.create(tile54);
		 this.rdbElementDao.create(tile55);
		 this.rdbElementDao.create(tile56);
		 this.rdbElementDao.create(tile57);
		 this.rdbElementDao.create(tile58);
		 this.rdbElementDao.create(tile59);
		 this.rdbElementDao.create(tile60);
		 this.rdbElementDao.create(tile61);
		 this.rdbElementDao.create(tile62);
		 this.rdbElementDao.create(tile63);
		 this.rdbElementDao.create(tile64);
		 this.rdbElementDao.create(tile65);
		 this.rdbElementDao.create(tile66);
		 this.rdbElementDao.create(tile67);
		 this.rdbElementDao.create(tile68);
		 this.rdbElementDao.create(tile69);
		 this.rdbElementDao.create(tile70);
		 this.rdbElementDao.create(tile71);
		 this.rdbElementDao.create(tile72);
		 this.rdbElementDao.create(tile73);
		 this.rdbElementDao.create(tile74);
		 this.rdbElementDao.create(tile75);
		 this.rdbElementDao.create(tile76);
		 this.rdbElementDao.create(tile77);
		 this.rdbElementDao.create(tile78);
		 this.rdbElementDao.create(tile79);
		 this.rdbElementDao.create(tile80);
		 this.rdbElementDao.create(tile81);
		 this.rdbElementDao.create(tile82);
		 this.rdbElementDao.create(tile83);
		 this.rdbElementDao.create(tile84);
		 this.rdbElementDao.create(tile85);
		 this.rdbElementDao.create(tile86);
		 this.rdbElementDao.create(tile87);
		 this.rdbElementDao.create(tile88);
		 this.rdbElementDao.create(tile89);
		 this.rdbElementDao.create(tile90);
		 this.rdbElementDao.create(tile91);
		 this.rdbElementDao.create(tile92);
		 this.rdbElementDao.create(tile93);
		 this.rdbElementDao.create(tile94);
		 this.rdbElementDao.create(tile95);
		 this.rdbElementDao.create(tile96);
		 this.rdbElementDao.create(tile97);
		 this.rdbElementDao.create(tile98);
		 this.rdbElementDao.create(tile99);
		 this.rdbElementDao.create(tile100);
		 this.rdbElementDao.create(snake1);
		 this.rdbElementDao.create(snake2);
		 this.rdbElementDao.create(snake3);
		 this.rdbElementDao.create(snake4);
		 this.rdbElementDao.create(snake5);
		 this.rdbElementDao.create(ladder1);
		 this.rdbElementDao.create(ladder2);
		 this.rdbElementDao.create(ladder3);
		 this.rdbElementDao.create(ladder4);
		 this.rdbElementDao.create(ladder5);
		 this.rdbElementDao.create(ladder6);
		 this.rdbElementDao.create(trapoline1);
		 this.rdbElementDao.create(trapoline2);
		 this.rdbElementDao.create(trapoline3);
		 this.rdbElementDao.create(trapoline4);
		 this.rdbElementDao.create(board);
	*/	 
		 System.out.println(" -- Database has been initialized");
	 }
}
